$(document).ready(function(){
	FastClick.attach(document.body);//fastclick
	$('.list').click(function(){
		$('.meng').show();
	});
	$('.close').click(function(){
		$(this).parents('.meng').hide();
	});
});